import { AppLink } from '@/lib/router'

interface NavLink {
  label: string
  href: string
  /** True for in-app router paths (client-side nav); false/absent for hash anchors. */
  route?: boolean
}

/** Root-relative so they work from non-home routes (e.g. /games) too. */
const siteLinks: NavLink[] = [
  { label: 'About', href: '/#about' },
  { label: 'Focus', href: '/#skills' },
  { label: 'Products', href: '/#products' },
  { label: 'Open Source', href: '/#oss' },
  { label: 'Games', href: '/games', route: true },
  { label: 'Writing', href: '/#blog' },
  { label: 'Contact', href: '/#contact' },
]

const elsewhereLinks: NavLink[] = [
  { label: 'GitHub', href: 'https://github.com/luongnv89' },
  { label: 'LinkedIn', href: 'https://linkedin.com/in/luongnv89' },
  { label: 'X', href: 'https://x.com/luongnv89' },
  { label: 'Medium', href: 'https://medium.com/@luongnv89' },
  { label: 'Substack', href: 'https://luongnv89.substack.com/' },
  { label: 'Bluesky', href: 'https://bsky.app/profile/luongnv89.bsky.social' },
]

const linkClass = 'text-sm text-[var(--text-secondary)] hover:text-[var(--text-primary)] transition-colors'

interface FooterProps {
  className?: string
}

export function Footer({ className = '' }: FooterProps) {
  const currentYear = new Date().getFullYear()

  return (
    <footer className={`border-t border-[var(--border)] py-12 ${className}`}>
      <div className="container-custom">
        <div className="grid md:grid-cols-12 gap-10">
          <div className="md:col-span-5">
            <p className="flex items-center gap-2">
              <span className="inline-block h-2 w-2 rounded-full bg-[var(--accent)]" aria-hidden />
              <span className="font-medium text-[var(--text-primary)]">Luong Nguyen</span>
            </p>
            <p className="mt-3 max-w-xs text-sm text-[var(--text-secondary)]">
              AI &amp; Cybersecurity engineer in Paris. Building tooling for AI agents and
              securing the networks they run on.
            </p>
          </div>

          <nav className="md:col-span-3" aria-label="Site">
            <p className="eyebrow">Site</p>
            <ul className="mt-4 flex flex-col gap-2.5">
              {siteLinks.map(({ label, href, route }) => (
                <li key={label}>
                  {route ? (
                    <AppLink to={href} className={linkClass}>
                      {label}
                    </AppLink>
                  ) : (
                    <a href={href} className={linkClass}>
                      {label}
                    </a>
                  )}
                </li>
              ))}
            </ul>
          </nav>

          <nav className="md:col-span-4" aria-label="Elsewhere">
            <p className="eyebrow">Elsewhere</p>
            <ul className="mt-4 flex flex-col gap-2.5">
              {elsewhereLinks.map(({ label, href }) => (
                <li key={label}>
                  <a
                    href={href}
                    target="_blank"
                    rel="noopener noreferrer"
                    className={linkClass}
                  >
                    {label}
                  </a>
                </li>
              ))}
            </ul>
          </nav>
        </div>

        <div className="mt-12 pt-6 border-t border-[var(--border)] flex flex-col sm:flex-row sm:justify-between gap-3 text-xs text-[var(--text-muted)]">
          <p>&copy; {currentYear} Luong Nguyen</p>
          <p>
            All project logos were generated by the <code>logo-designer</code> skill in my{' '}
            <a
              href="https://github.com/luongnv89/skills"
              target="_blank"
              rel="noopener noreferrer"
              className="underline decoration-[var(--border-hover)] underline-offset-2 hover:text-[var(--text-primary)] transition-colors"
            >
              skills repository
            </a>
            .
          </p>
        </div>
      </div>
    </footer>
  )
}
