import { ArrowUpRight } from 'lucide-react'
import { PortfolioCard } from './PortfolioCard'
import portfolioData from '@/data/portfolio.json'

/** First N entries in portfolio.json are the featured OSS grid; the rest go in "More OSS projects". */
const FEATURED_OSS_LIMIT = 8

interface Product {
  name: string
  tagline: string
  description: string
  url: string
  logo: string
}

const productProjects: Product[] = [
  {
    name: 'Milo',
    tagline: 'iOS · Voice AI',
    description: 'Hands-free AI for Siri & CarPlay — "Hey Siri, ask MILO…" routes your voice to GPT, Claude, Gemini, or 200+ models.',
    url: 'https://askmilo.pro',
    logo: '/images/projects/milo.svg',
  },
  {
    name: 'TextWiz',
    tagline: 'macOS · Writing',
    description: 'Local-first macOS app that runs AI "wizards" on selected text via a global hotkey (⌘⇧Space). On-device by default, no servers.',
    url: 'https://www.textwiz.pro',
    logo: '/images/projects/textwiz.svg',
  },
  {
    name: 'devstats',
    tagline: 'Web · Analytics',
    description: 'GitHub stats dashboard with contribution graphs, language breakdowns, and shareable profile cards.',
    url: 'https://devstats.info',
    logo: '/images/projects/devstats.svg',
  },
  {
    name: 'custats',
    tagline: 'Web · Analytics',
    description: 'Claude + Codex usage tracking — monitor token spend, sessions, and model activity in one dashboard.',
    url: 'https://custats.info',
    logo: '/images/projects/custats.svg',
  },
  {
    name: 'music',
    tagline: 'Web · CLI',
    description: 'A terminal-native music player — the marketing site and docs for the music CLI.',
    url: 'https://music-cli.luongnv.com',
    logo: '/images/projects/music-cli.svg',
  },
]

export function Portfolio() {
  const featuredOssProjects = portfolioData.projects
    .slice(0, FEATURED_OSS_LIMIT)
    .map((project) => ({
      ...project,
      displayName: project.name === 'agent-skill-manager' ? 'asm' : project.name,
    }))

  const remainingOssProjects = portfolioData.projects.slice(FEATURED_OSS_LIMIT)

  return (
    <section id="portfolio" className="section bg-[var(--bg-secondary)]">
      <div className="container-custom">
        <h2 className="section-title">OSS Projects</h2>
        <p className="section-subtitle max-w-3xl mb-8">
          Selected OSS work and live products. All logos in this portfolio were generated by the <code>logo-designer</code> skill in the <a href="https://github.com/luongnv89/skills" target="_blank" rel="noopener noreferrer" className="underline">skills repository</a>.
        </p>

        <div className="space-y-12">
          <div>
            <p className="section-subtitle max-w-2xl mb-6">
              Featured OSS projects.
            </p>
            <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-4">
              {featuredOssProjects.map((project) => (
                <PortfolioCard key={`oss-${project.name}`} project={project} />
              ))}
            </div>

            {remainingOssProjects.length > 0 && (
              <details className="mt-6 rounded-xl border border-[var(--border)] bg-[var(--bg-primary)]/40">
                <summary className="cursor-pointer list-none px-4 py-3 text-sm font-medium text-[var(--text-primary)] flex items-center justify-between">
                  <span>More OSS projects</span>
                  <span className="text-[var(--text-muted)]">Open to expand</span>
                </summary>
                <div className="px-4 pb-4">
                  <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-4">
                    {remainingOssProjects.map((project) => (
                      <PortfolioCard key={`oss-more-${project.name}`} project={project} />
                    ))}
                  </div>
                </div>
              </details>
            )}
          </div>

          <div>
            <p className="section-subtitle max-w-2xl mb-6">
              Products.
            </p>
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
              {productProjects.map((project) => (
                <a
                  key={project.name}
                  href={project.url}
                  target="_blank"
                  rel="noopener noreferrer"
                  aria-label={`${project.name} — visit website`}
                  className="group relative flex h-full flex-col overflow-hidden rounded-2xl border border-[var(--border)] bg-[var(--bg-secondary)] p-5 transition-all duration-300 hover:-translate-y-1 hover:border-[var(--accent)] hover:shadow-[0_18px_40px_-22px_var(--accent-glow)] focus-ring"
                >
                  {/* Accent wash that fades in on hover */}
                  <span
                    aria-hidden="true"
                    className="pointer-events-none absolute inset-0 opacity-0 transition-opacity duration-300 group-hover:opacity-100"
                    style={{
                      background:
                        'radial-gradient(120% 80% at 0% 0%, var(--accent-glow), transparent 60%)',
                    }}
                  />

                  {/* Header: logo tile + name + tagline */}
                  <div className="relative flex items-center gap-4">
                    <span
                      className="flex h-12 w-12 shrink-0 items-center justify-center rounded-xl border border-[var(--border)] bg-[var(--bg-primary)] transition-colors duration-300 group-hover:border-[var(--border-hover)]"
                      style={{
                        backgroundImage:
                          'radial-gradient(circle, var(--border) 1px, transparent 1px)',
                        backgroundSize: '10px 10px',
                      }}
                    >
                      <img
                        src={project.logo}
                        alt={project.name}
                        loading="lazy"
                        className="h-9 w-9 rounded-lg object-contain drop-shadow-sm"
                      />
                    </span>
                    <div className="min-w-0">
                      <h3 className="truncate text-lg font-semibold text-[var(--text-primary)]">
                        {project.name}
                      </h3>
                      <span className="mt-0.5 inline-block text-[11px] font-medium uppercase tracking-[0.18em] text-[var(--text-muted)]">
                        {project.tagline}
                      </span>
                    </div>
                  </div>

                  {/* Description */}
                  <p className="relative mt-4 flex-grow text-sm leading-relaxed text-[var(--text-secondary)]">
                    {project.description}
                  </p>

                  {/* Footer: domain + arrow */}
                  <div className="relative mt-5 flex items-center justify-between border-t border-[var(--border)] pt-4">
                    <span className="truncate font-mono text-sm font-medium text-accent">
                      {project.url.replace(/^https?:\/\//, '').replace(/\/$/, '')}
                    </span>
                    <ArrowUpRight
                      size={18}
                      className="shrink-0 text-[var(--text-muted)] transition-all duration-300 group-hover:-translate-y-0.5 group-hover:translate-x-0.5 group-hover:text-[var(--accent)]"
                    />
                  </div>
                </a>
              ))}
            </div>
          </div>
        </div>
      </div>
    </section>
  )
}
