import { PortfolioCard } from './PortfolioCard'
import portfolioData from '@/data/portfolio.json'
import privatePortfolioData from '@/data/private-portfolio.json'

const FEATURED_OSS_LIMIT = 8

const productProjects = [
  {
    name: 'devstats',
    description: 'GitHub stats dashboard at devstats.info.',
    url: 'https://devstats.info',
  },
  {
    name: 'custats',
    description: 'Claude + Codex usage tracking at custats.info.',
    url: 'https://custats.info',
  },
  {
    name: 'music',
    description: 'Music CLI website at music-cli.luongnv.com.',
    url: 'https://music-cli.luongnv.com',
  },
]

const privateProjectNames = ['travels', 'ideas', 'notes', 'blogs']

export function Portfolio() {
  const sortedOssProjects = [...portfolioData.projects].sort(
    (a, b) => (b.stars ?? 0) - (a.stars ?? 0),
  )

  const featuredOssProjects = sortedOssProjects.slice(0, FEATURED_OSS_LIMIT).map((project) => ({
    ...project,
    displayName: project.name === 'agent-skill-manager' ? 'asm' : project.name,
  }))

  const remainingOssProjects = sortedOssProjects.slice(FEATURED_OSS_LIMIT)

  const personalFlowProjects = privatePortfolioData.projects.filter(({ name }) =>
    privateProjectNames.includes(name),
  )

  return (
    <section id="portfolio" className="section bg-[var(--bg-secondary)]">
      <div className="container-custom">
        <h2 className="section-title">OSS Projects</h2>
        <p className="section-subtitle max-w-3xl mb-8">
          Selected OSS work, live products, and my personal flow. All logos in this portfolio were generated by the <code>logo-designer</code> skill in the <a href="https://github.com/luongnv89/skills" target="_blank" rel="noopener noreferrer" className="underline">skills repository</a>.
        </p>

        <div className="space-y-12">
          <div>
            <p className="section-subtitle max-w-2xl mb-6">
              Featured OSS projects.
            </p>
            <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-4">
              {featuredOssProjects.map((project) => (
                <PortfolioCard key={`oss-${project.name}`} project={project} />
              ))}
            </div>

            {remainingOssProjects.length > 0 && (
              <details className="mt-6 rounded-xl border border-[var(--border)] bg-[var(--bg-primary)]/40">
                <summary className="cursor-pointer list-none px-4 py-3 text-sm font-medium text-[var(--text-primary)] flex items-center justify-between">
                  <span>More OSS projects</span>
                  <span className="text-[var(--text-muted)]">Open to expand</span>
                </summary>
                <div className="px-4 pb-4">
                  <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-4">
                    {remainingOssProjects.map((project) => (
                      <PortfolioCard key={`oss-more-${project.name}`} project={project} />
                    ))}
                  </div>
                </div>
              </details>
            )}
          </div>

          <div>
            <p className="section-subtitle max-w-2xl mb-6">
              My personal assistant: Olak (<a href="https://openclaw.ai" target="_blank" rel="noopener noreferrer" className="underline">OpenClaw</a>), Telegram (for communication), Github based CMS.
            </p>
            <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-4">
              {personalFlowProjects.map((project) => (
                <PortfolioCard key={`private-${project.name}`} project={project} />
              ))}
            </div>
          </div>

          <div>
            <p className="section-subtitle max-w-2xl mb-6">
              Products.
            </p>
            <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
              {productProjects.map((project) => (
                <a
                  key={project.name}
                  href={project.url}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="card p-5 block hover:border-[var(--accent)] transition-colors duration-200 focus-ring"
                >
                  <div className="flex items-start justify-between gap-4">
                    <div>
                      <h3 className="text-lg font-semibold text-[var(--text-primary)]">{project.name}</h3>
                      <p className="mt-2 text-sm text-[var(--text-secondary)] leading-relaxed">
                        {project.description}
                      </p>
                    </div>
                    <span className="text-xs uppercase tracking-[0.2em] text-[var(--text-muted)]">
                      Website
                    </span>
                  </div>
                  <div className="mt-5 text-sm text-accent font-medium">
                    {project.url.replace(/^https?:\/\//, '')}
                  </div>
                </a>
              ))}
            </div>
          </div>
        </div>
      </div>
    </section>
  )
}
