import { PortfolioCard } from './PortfolioCard'
import portfolioData from '@/data/portfolio.json'
import privatePortfolioData from '@/data/private-portfolio.json'

export function Portfolio() {
  return (
    <section id="portfolio" className="section bg-[var(--bg-secondary)]">
      <div className="container-custom">
        <h2 className="section-title">Portfolio</h2>

        <div className="space-y-12">
          <div>
            <p className="section-subtitle max-w-2xl mb-6">
              Open-source projects.
            </p>
            <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-4">
              {portfolioData.projects.map((project) => (
                <PortfolioCard key={`oss-${project.name}`} project={project} />
              ))}
            </div>
          </div>

          <div>
            <p className="section-subtitle max-w-2xl mb-6">
              Some private projects. All logos were generated by the <code>logo-designer</code> skill in the <a href="https://github.com/luongnv89/skills" target="_blank" rel="noopener noreferrer" className="underline">skills repository</a>.
            </p>
            <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-4">
              {privatePortfolioData.projects.map((project) => (
                <PortfolioCard key={`private-${project.name}`} project={project} />
              ))}
            </div>
          </div>
        </div>
      </div>
    </section>
  )
}
